CREATE TABLE hotel_monitors (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                active BOOLEAN NOT NULL,
                                adults INTEGER NOT NULL,
                                alert_sent BOOLEAN NOT NULL,
                                check_in DATE,
                                check_out DATE,
                                hotel_url VARCHAR(255),
                                rooms INTEGER NOT NULL,
                                target_price DOUBLE PRECISION NOT NULL,
                                CONSTRAINT hotel_monitors_pkey PRIMARY KEY (id)
);

CREATE TABLE price_history (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               checked_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                               price DOUBLE PRECISION NOT NULL,
                               monitor_id BIGINT NOT NULL,
                               CONSTRAINT price_history_pkey PRIMARY KEY (id),
                               CONSTRAINT fk_price_history_monitor
                                   FOREIGN KEY (monitor_id)
                                       REFERENCES hotel_monitors(id)
);